# Starter pipeline
- task: Prisma Cloud IaC Scan@1
  inputs:
    Path: '.'
    prismaCloudService: 'Prisma IaC'
    High: '0'
    Medium: '0'
    Low: '0'
    Operator: 'or'
    Tags: 'repo:iac-scan'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
